const COUNTRY = {
	AUSTRALIA : 'Australia',
	BELARUS : 'Belarus',
	BELGIUM : 'Belgium',
	BULGARIA : 'Bulgaria',
	CANADA : 'Canada',
	CHINA : 'China',
	CZECH_REPUBLIC : 'Czech Republic',
	GERMANY : 'Germany',
	HONG_KONG : 'Hong Kong',
	HUNGARY : 'Hungary',
	INDIA : 'India',
	IRELAND : 'Ireland',
	KAZAKHSTAN : 'Kazakhstan',
	MALAYSIA : 'Malaysia',
	MEXICO : 'Mexico',
	NETHERLANDS : 'Netherlands',
	POLAND : 'Poland',
	RUSSIAN_FEDERATION : 'Russian Federation',
	SINGAPORE : 'Singapore',
	SPAIN : 'Spain',
	SWEDEN : 'Sweden',
	SWITZERLAND : 'Switzerland',
	UKRAINE : 'Ukraine',
	UNITED_ARAB_EMIRATES : 'United Arab Emirates',
	UNITED_KINGDOM : 'United Kingdom',
	UNITED_STATES : 'United States',
};

module.exports = COUNTRY;